function [uhl_gene_names, uhl_cluster, uhl_log2_fc] = readUhlitzTimeSeries

% this function reads and processes the Uhlitz 2017 dataset. 
% The dataset is accessible at: 
% https://doi.org/10.1371/journal.pone.0041169.s003
% The paper is accessble at:
% https://doi.org/10.15252/msb.20177554

% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\MATLAB\20240808 Pommerenke RY crunch\1_raw_data\Uhlitz_log2FC_4OHT.csv
%
% Auto-generated by MATLAB on 15-Aug-2024 16:39:13
% Rosemary Yu. Last update: 2024-08-15

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ID_REF", "SYMBOL", "cluster", "UT_1", "UT_3", "T05h", "T1h", "T2h_1", "T2h_2", "T2h_3", "T3h", "T4h", "T6h", "T8h", "T10h"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["ID_REF", "SYMBOL", "cluster"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ID_REF", "SYMBOL", "cluster"], "EmptyFieldRule", "auto");

% Import the data
uhlitz = readtable("\1_raw_data\Uhlitz_log2FC_4OHT.csv", opts);

% pull out gene names & cluster 
uhl_gene_names = uhlitz(:,2);
uhl_gene_names = table2array(uhl_gene_names);
uhl_cluster = uhlitz(:,3);
uhl_cluster = table2array(uhl_cluster);

% pull out gene expression data & cleanup
t0 = zeros (length(uhl_gene_names), 1);

uhl_t2h = table2array(uhlitz (:, 8:10));
uhl_t2h = mean(uhl_t2h, 2);

uhl_log2_fc = horzcat (t0, table2array(uhlitz(:,6:7)), ...
    uhl_t2h, table2array(uhlitz(:,11:15)));

end