function [pom_gene_names, pom_log2_fc, pom_clusters] = readPommerenke

% this function reads and processes the Pommerenke 2012 dataset. Genes with
% less than 5 entries with non-zero log2FC are filtered out. 
% The dataset is accessible at: 
% https://doi.org/10.1371/journal.pone.0041169.s003
% The paper is accessble at:
% https://doi.org/10.1371/journal.pone.0041169
%
% Auto-generated by MATLAB on 24-Nov-2023 13:25:55%
% 
% Rosemary Yu. Last update: 2024-08-08
% Chen Chen. Last update: 2024-09-06


% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 18);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:R3596";

% Specify column names and types
opts.VariableNames = ["ClusterNumber", "ShortName", "Var3", "Var4", "MockinfectionAbsoluteValue", "DpiFc", "DpiFc1", "DpiFc2", "DpiFc3", "DpiFc4", "DpiFc5", "DpiFc6", "DpiFc7", "DpiFc8", "DpiFc9", "DpiFc10", "DpiFc11", "DpiFc12"];
opts.SelectedVariableNames = ["ClusterNumber", "ShortName", "MockinfectionAbsoluteValue", "DpiFc", "DpiFc1", "DpiFc2", "DpiFc3", "DpiFc4", "DpiFc5", "DpiFc6", "DpiFc7", "DpiFc8", "DpiFc9", "DpiFc10", "DpiFc11", "DpiFc12"];
opts.VariableTypes = ["double", "string", "char", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["ShortName", "Var3", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ShortName", "Var3", "Var4"], "EmptyFieldRule", "auto");

% Import the data
pommerenke = readtable("1_raw_data\pone.0041169.s003.xls", opts, "UseExcel", false);

% Replace NaN with 0 (log2 of 1)
pom_log2_fc = table2array(pommerenke (:, 4:16));
pom_log2_fc (isnan (pom_log2_fc))=0;
pommerenke (:, 4:16) = array2table(pom_log2_fc);

% filter for >=5 entries with non-zero log2FC
filter = sum(pom_log2_fc~=0,2);
idx = find(filter>=5);
pommerenke = pommerenke(idx,:);
pom_log2_fc = pom_log2_fc(idx,:);

% Pull out clusters
pom_clusters = table2array (pommerenke (:,1));

% add column of 0 for day 0
d0 = zeros (length(pom_log2_fc), 1);
pom_log2_fc = horzcat (d0, pom_log2_fc);

% pull out gene names 
pom_gene_names = pommerenke (:, 2);
pom_gene_names = table2array(pom_gene_names);


end



